export const StatusOnibus = {
    NOVO: 'NOVO',
    DISPONIVEL: 'DISPONIVEL',
    EM_OPERACAO: 'EM_OPERACAO',
    EM_MANUTENCAO: 'EM_MANUTENCAO',
    EM_REFORMA: 'EM_REFORMA',
    APOSENTADO: 'APOSENTADO',
    VENDIDO: 'VENDIDO',
};